%% Line 26 error function
figure
syscal.plotSensorPose(state(x+idxs:phi+idxs,1)')
hold on ;
plot(state(x+idxm),state(y+idxm), 'o')
disp(['phi + pose' ...
num2str(mltools.rad2deg(state(phi+idxs)+scal.measureAoa{i}(j))) ...
' pose '...
num2str(mltools.rad2deg(state(phi+idxs)))...
' phi '...
num2str(mltools.rad2deg(scal.measureAoa{i}(j)))...
' atan2 measure '...
num2str(mltools.rad2deg(atan2(state(y+idxm)-state(y+idxs),(state(x+idxm)-state(x+idxs)))))...
' Result = '...
num2str(tan(state(phi+idxs)+scal.measureAoa{i}(j))-((state(y+idxm)-state(y+idxs))/(state(x+idxm)-state(x+idxs))))...
]);
