function [scal, result] = calcFsolveRaw(scene, posVar, sensVar, alg)

scal = syscal.createRunParameters(scene, 'rnd', posVar, sensVar);
scal.userData.plotState = true;

fun = @(x) syscal.calcStateRaw(x, scal);

opt = optimset('display', 'iter'...
    , 'maxfunevals', 500*numel(scal.stateCurrent) ...
    , 'maxiter', 500*numel(scal.stateCurrent) ...
    , 'plotfcns', @optimplotfval...
    , 'tolfun', 1e-6...
    , 'tolx', 1e-6...
    ...    , 'Jacobian', 'on'...
    , 'Algorithm', alg...
    ..., 'Algorithm', 'trust-region-dogleg'...%DEFAULT
    ...    , 'Algorithm', 'trust-region-reflective'...
    ...    , 'Algorithm', {'levenberg-marquardt', 0.01'}...
    ...    , 'DiffMaxChange', 1 ...
    ...    , 'DiffMinChange', 1e-3 ...
    );

P.objective = fun;
P.x0 = scal.stateCurrent;
P.options = opt;
P.solver = 'fsolve';


[result.state, result.fval, result.exitflag, result.output ] = fsolve(P);
